<table id="product-table" class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>@lang('product.name')</th>
            <th>@lang('product.description')</th>
            <th>@lang('product.price')</th>
            <th>@lang('default.actions')</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
        <tr>
            <th>@lang('product.name')</th>
            <th>@lang('product.description')</th>
            <th>@lang('product.price')</th>
            <th>@lang('default.actions')</th>
    </tfoot>
</table>